# Generated by Django 4.0 on 2021-12-31 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, verbose_name='deleted_at'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
    ]
