# Generated by Django 4.0 on 2022-01-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_inheritedstudentuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='experience',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='qualfication',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
