# Generated by Django 4.0 on 2022-01-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0005_alter_studentuser_deleted_at_alter_tutor_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
