# Generated by Django 4.0 on 2022-01-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0006_alter_studentuser_deleted_at_alter_tutor_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='deleted_at',
        ),
    ]
