# Generated by Django 4.0 on 2022-01-07 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0007_remove_studentuser_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='user',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='firstname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='lastname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
