# Generated by Django 4.0 on 2022-01-07 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hiring', '0008_remove_studentuser_gender_remove_studentuser_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=200, null=True)),
                ('mobile', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='qualfication',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='type1',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tutor',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.AddField(
            model_name='students',
            name='tutor',
            field=models.ManyToManyField(blank=True, to='hiring.Tutor'),
        ),
    ]
