# Generated by Django 4.0 on 2022-01-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0010_students_created_at_students_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='salary',
        ),
        migrations.CreateModel(
            name='TutorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('position', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('experience', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], max_length=200, null=True)),
                ('apply_date', models.DateField()),
                ('tutorname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
