# Generated by Django 4.0 on 2022-01-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0011_remove_tutor_description_remove_tutor_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tutor',
            name='description',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='salary',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='TutorPost',
        ),
    ]
