# Generated by Django 4.0 on 2022-01-10 02:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0012_remove_students_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='position',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='salary',
        ),
        migrations.AddField(
            model_name='students',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.CreateModel(
            name='TutorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('position', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('experience', models.IntegerField(null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiring.tutor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
