# Generated by Django 4.0 on 2022-01-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0013_remove_tutor_description_remove_tutor_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorpost',
            old_name='position',
            new_name='subject',
        ),
    ]
