# Generated by Django 4.0 on 2022-01-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0016_alter_tutorpost_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorpost',
            name='level',
            field=models.CharField(choices=[('lower primary', 'lower primary'), ('higher primary', 'higher primary'), ('high school', 'high school'), ('graduation', 'graduation')], max_length=200, null=True),
        ),
    ]
