# Generated by Django 4.0 on 2022-01-13 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0017_alter_tutorpost_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tutorpost',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tutorpost',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='students',
            name='created_Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='updated_Date',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_date'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='created_Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='updated_Date',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_date'),
        ),
        migrations.AddField(
            model_name='tutorpost',
            name='created_Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorpost',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='tutorpost',
            name='updated_Date',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_date'),
        ),
    ]
