# Generated by Django 4.0 on 2022-01-13 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0018_remove_students_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorpost',
            old_name='image',
            new_name='tutorpost',
        ),
    ]
