# Generated by Django 4.0 on 2022-01-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0019_rename_image_tutorpost_tutorpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorpost',
            name='tutorpost',
        ),
    ]
