# Generated by Django 4.0.1 on 2022-01-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0021_studentpost_alter_students_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpost',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
