# Generated by Django 4.0.1 on 2022-01-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0022_studentpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpost',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
