# Generated by Django 4.0.1 on 2022-01-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0023_studentpost_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpost',
            name='status',
        ),
    ]
