# Generated by Django 4.0.1 on 2022-01-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0024_remove_studentpost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorpost',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
