# Generated by Django 4.0.1 on 2022-01-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0025_tutorpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorpost',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
