# Generated by Django 4.0.1 on 2022-01-30 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0026_alter_tutorpost_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorpost',
            name='status',
        ),
    ]
